// adminMVC/errors/Error.js

export { default as DBConnectionError } from './DBErrors/DBConnectionError.js';
export { default as RegionAlredyExistsError } from './DBErrors/RegionAlredyExistsError.js'
export { default as NoDataToUpdateError } from './UserErrors/NoDataToUpdateError.js'
export { default as RegionDoesntExistsError } from './DBErrors/RegionDoesntExistsError.js'
export { default as DBCannotCreateError } from './DBErrors/DBCannotCreateError.js'
export { default as FacultadAlredyExistsError } from './DBErrors/FacultadAlredyExistsError.js'
export { default as FacultadDoesntExistsError } from './DBErrors/FacultadDoesntExistsError.js'
export { default as AreaAcademicaAlredyExistsError } from './DBErrors/AreaAcademicaAlredyExistsError.js'
export { default as AreaAcademicaDoesntExistsError } from './DBErrors/AreaAcademicaDoesntExistsError.js'
export { default as ExperienciaEducativaAlredyExistsError } from './DBErrors/ExperienciaEducativaAlredyExistsError.js'
export { default as ExperienciaEducativaDoesntExistsError } from './DBErrors/ExperienciaEducativaDoesntExistsError.js'
export { default as ProgramaEducativoAlredyExistsError } from './DBErrors/ProgramaEducativoAlredyExistsError.js'
export { default as ProgramaEducativoDoesntExistsError } from './DBErrors/ProgramaEducativoDoesntExistsError.js'
export { default as NivelEducativoAlredyExistsError } from './DBErrors/NivelEducativoAlredyExistsError.js'
export { default as NivelEducativoDoesntExistsError } from './DBErrors/NivelEducativoDoesntExistsError.js'
export { default as PeriodoAlredyExistsError } from './DBErrors/PeriodoAlredyExistsError.js'
export { default as PeriodoDoesntExistsError } from './DBErrors/PeriodoDoesntExistsError.js'
export { default as AcademiaAlredyExistsError } from './DBErrors/AcademiaAlredyExistsError.js'
export { default as AcademiaDoesntExistsError } from './DBErrors/AcademiaDoesntExistsError.js'
export { default as AdminAlredyExistsError } from './loginErrors/AdminAlredyExistsError.js'
export { default as AdminDoesntExitsError } from './loginErrors/AdminDoesntExistsError.js'
export { default as NotFoundError } from './DBErrors/NotFoundError.js'